### ISSUE TITLE
Auto update system for game

### ISSUE THREAD

**Issue by Zorz42** [Zorz42/Terralistic#47]

**Comment by iKramp** [comment]
Have a file that has last update for each file saved on both client and server. when the game starts it checks for updates (comparing updates for each file). if there is an update it should ask the player if it should update immediately (closes the game and starts a shell script or starts the script when player closes the game). shell script checks differences for each file separately and downloads changed/new files only. In case file gets deleted it can be regenerated using system's file change time data however this should only be used as a last resort (that's why there is a file that stores the data) as the user could mess with the files and thus trick the game into not updating
